#include "cudaRuntimeImpl.h"
#include "base_address.h"
#include "api.h"
#include "cuda_runtime.h"
#include "def.h"
#include "macros.h"
#include "structures.h"
#include <bits/stdint-uintn.h>
#include <cstddef>
#include <iostream>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <vortex.h>
#include <fstream>
#include <limits>
#include <vector>
#include <map>
#include <sstream>

// Global variable to support CudaMemcpytoSymbol
//NOTE: old approach used staging device buffer — replaced with inline args
//std::vector<std::vector<uint64_t> >  memcpy_symbol;
//std::vector<uint64_t> memcpy_symbol_single;
struct MemcpySymbolEntry {
  uint64_t dst_addr;   // symbol device address
  size_t   size;       // data size in bytes
  std::vector<uint8_t> data; // raw host bytes
};
std::vector<MemcpySymbolEntry> memcpy_symbol;
//create string vector
std::vector<std::string> symbol_name_vector;

// DXA descriptor entries (programmed before kernel launch)
struct DxaDescEntry {
  uint32_t slot;
  uint64_t base_addr;
  uint32_t size0, size1;
  uint32_t stride0_bytes;
  uint32_t tile0, tile1;
  uint32_t elem_bytes;
};
std::vector<DxaDescEntry> dxa_descriptors;

// Auto-DXA descriptor — reads dxa_descriptors.txt (generated by kernelTranslator)
// to auto-program DCR registers without manual cudaDxaProgramDesc2D calls. TESTED+PASSED.
struct DxaAutoDescEntry {
  std::string kernel_name;
  uint32_t slot;
  int ptr_arg_idx, dim0_arg_idx, dim1_arg_idx;
  uint32_t tile0, tile1, elem_bytes;
};
static std::vector<DxaAutoDescEntry> dxa_auto_descriptors;
static bool dxa_auto_loaded = false;

static void load_dxa_auto_descriptors() {
  if (dxa_auto_loaded) return;
  dxa_auto_loaded = true;
  std::ifstream ifs("dxa_descriptors.txt");
  if (!ifs.is_open()) return;
  std::string line;
  while (std::getline(ifs, line)) {
    if (line.empty() || line[0] == '#') continue;
    DxaAutoDescEntry e;
    std::istringstream iss(line);
    iss >> e.kernel_name >> e.slot >> e.ptr_arg_idx
        >> e.dim0_arg_idx >> e.dim1_arg_idx
        >> e.tile0 >> e.tile1 >> e.elem_bytes;
    if (!iss.fail()) dxa_auto_descriptors.push_back(e);
  }
}

// API for host code to program DXA descriptors before kernel launch
extern "C" void cudaDxaProgramDesc2D(uint32_t slot, uint64_t base_addr,
                                      uint32_t size0, uint32_t size1,
                                      uint32_t stride0_bytes,
                                      uint32_t tile0, uint32_t tile1,
                                      uint32_t elem_bytes) {
  dxa_descriptors.push_back({slot, base_addr, size0, size1,
                             stride0_bytes, tile0, tile1, elem_bytes});
}

// Debug print macros — enabled by setting CUPBOP_DEBUG=1 environment variable
static bool cupbop_debug_enabled() {
    static bool enabled = (std::getenv("CUPBOP_DEBUG") != nullptr);
    return enabled;
}
#define DBG_PRINT(...) do { if (cupbop_debug_enabled()) printf(__VA_ARGS__); } while(0)
#define DBG_COUT(x) do { if (cupbop_debug_enabled()) std::cout << x; } while(0)

#define RT_CHECK(_expr)                                         \
   do {                                                         \
     int _ret = _expr;                                          \
     if (0 == _ret)                                             \
       break;                                                   \
     printf("Error: '%s' returned %d!\n", #_expr, (int)_ret);   \
     std::abort();                                              \
   } while (false)


// Different structure based on the architecture
#ifdef VORTEX_ARCHITECTURE_64
  struct alignas(4) context_t {
    uint32_t num_groups[3];
    uint32_t global_offset[3];
    uint32_t local_size[3];
    char * printf_buffer;
    uint32_t printf_buffer_position;
    uint32_t printf_buffer_capacity;
    uint32_t work_dim;
    uint32_t dyn_shared_mem_size;
  };

#else
  struct alignas(4) context_t {
    uint32_t num_groups[3];
    uint32_t global_offset[3];
    uint32_t local_size[3];
    uint32_t printf_buffer;
    uint32_t printf_buffer_position;
    uint32_t printf_buffer_capacity;
    uint32_t work_dim;
    uint32_t dyn_shared_mem_size;
  };
#endif


struct alignas(64) kernel_arg_t {
  context_t ctx;
  int kernel_idx;
  int num_args;
  uint64_t  args[0];
};

typedef void (*pfn_workgroup_func) (
  const void* args,
  const context_t* context,
  uint32_t group_x,
  uint32_t group_y,
  uint32_t group_z
);

class DeviceContext {
private:
  DeviceContext()
    : device_(nullptr)
    , staging_buf_(std::vector<uint8_t>())
    , staging_size_(0)
    , krnl_buffer_(nullptr)
    , args_buffer_(nullptr)
  {
    RT_CHECK(vx_dev_open(&device_));
  }

  ~DeviceContext() {
    if (device_ != nullptr) {
      // Cleanup buffers
      if (krnl_buffer_ != nullptr)
	vx_mem_free(krnl_buffer_);
      if (args_buffer_ != nullptr)
	vx_mem_free(args_buffer_);
      
      vx_dev_close(device_);
    }
  }

public:
  void cleanup_args() {
    if (args_buffer_ != nullptr) {
      vx_mem_free(args_buffer_);
      args_buffer_ = nullptr;
    }
  }

  void cleanup_krnl() {
    if (krnl_buffer_ != nullptr) {
      vx_mem_free(krnl_buffer_);
      krnl_buffer_ = nullptr;
    }
    last_krnl_path_.clear();
  }

  const std::string& last_krnl_path() const { return last_krnl_path_; }
  void set_last_krnl_path(const std::string& p) { last_krnl_path_ = p; }
private:

  vx_device_h device_;
  std::vector<uint8_t> staging_buf_;
  size_t staging_size_;

  // Buffers
  vx_buffer_h krnl_buffer_;
  vx_buffer_h args_buffer_;
  std::string last_krnl_path_;

  // Pointer manager
  struct MemoryInfo {
    vx_buffer_h buffer_handle;
    size_t size;
    uint64_t base_addr;

    MemoryInfo() : buffer_handle(nullptr), size(0), base_addr(0) {}
    MemoryInfo(vx_buffer_h handle, size_t sz, uint64_t base)
        : buffer_handle(handle), size(sz), base_addr(base) {}
  };
  std::map<void*, MemoryInfo> ptr_map;
  
public:
  static DeviceContext* instance() {
    static DeviceContext s_inst;
    return &s_inst;
  }

  vx_device_h device() {    
    return device_;
  }

  vx_buffer_h* krnl_buffer() {
    return &krnl_buffer_;
  }

  vx_buffer_h* args_buffer() {
    return &args_buffer_;
  }

  vx_buffer_h get_krnl_buf() {
    return krnl_buffer_;
  }

  vx_buffer_h get_args_buf() {
    return args_buffer_;
  }
  
  std::vector<uint8_t> staging_alloc(size_t size) {
    staging_buf_.resize(size);
    staging_size_ = size;
    return staging_buf_;
  }

  void dev_mem_alloc(int size, int flag, uint64_t* mem_addr) {
    vx_buffer_h mem_buffer = nullptr;

    // Allocate memory on device
    RT_CHECK(vx_mem_alloc(this->device(), size, flag, &mem_buffer));
    RT_CHECK(vx_mem_address(mem_buffer, mem_addr));  

    // Register pointer with its handler
    ptr_map[(void*)(*mem_addr)] = MemoryInfo(mem_buffer, size, *mem_addr);
  }

  void dev_mem_free(void* mem_addr) {
    if (ptr_map.find(mem_addr) != ptr_map.end()) {
      MemoryInfo& info = ptr_map[mem_addr];
      vx_mem_free(info.buffer_handle);
      ptr_map.erase(mem_addr);
    }
  }

  void copy_to_dev(uint64_t mem_addr, void* host_ptr, int count) {
    // 정확한 주소 매칭
    auto it = ptr_map.find((void*)mem_addr);
    if (it != ptr_map.end()) {
      RT_CHECK(vx_copy_to_dev(it->second.buffer_handle, host_ptr, 0, count));
      return;
    }
    // 오프셋 기반 검색 (Triton: 할당 블록 내부 주소)
    for (auto& pair : ptr_map) {
      const MemoryInfo& info = pair.second;
      if (mem_addr >= info.base_addr && mem_addr < (info.base_addr + info.size)) {
        size_t offset = mem_addr - info.base_addr;
        if (offset + count <= info.size) {
          RT_CHECK(vx_copy_to_dev(info.buffer_handle, host_ptr, offset, count));
          return;
        }
      }
    }
    printf("copy_to_dev: ERROR - mem_addr=0x%lx not found!\n", mem_addr);
    std::abort();
  }

  void copy_from_dev(uint64_t mem_addr, void* host_ptr, int count) {
    // 정확한 주소 매칭
    if (ptr_map.find((void*)mem_addr) != ptr_map.end()) {
      auto& info = ptr_map[(void*)mem_addr];
      RT_CHECK(vx_copy_from_dev(host_ptr, info.buffer_handle, 0, count));
      return;
    }
    // 오프셋 기반 검색 (Triton: 할당 블록 내부 주소)
    for (auto& pair : ptr_map) {
      const MemoryInfo& info = pair.second;
      if (mem_addr >= info.base_addr && mem_addr < (info.base_addr + info.size)) {
        size_t offset = mem_addr - info.base_addr;
        if (offset + count <= info.size) {
          RT_CHECK(vx_copy_from_dev(host_ptr, info.buffer_handle, offset, count));
          return;
        }
      }
    }
    printf("copy_from_dev: ERROR - mem_addr=0x%lx not found!\n", mem_addr);
    std::abort();
  }

  void cleanup() {
    if (device_ != nullptr) { 
      if (krnl_buffer_ != nullptr)
	vx_mem_free(krnl_buffer_);
      if (args_buffer_ != nullptr)
	vx_mem_free(args_buffer_);

      vx_dev_close(device_);
      device_ = nullptr;
    }
  }
};

auto DC_init = DeviceContext::instance();

uint64_t NUM_THREADS_VX, NUM_WARPS_VX, NUM_CORES_VX;
int caps_return1 = vx_dev_caps(DC_init->device(), VX_CAPS_NUM_THREADS, &NUM_THREADS_VX);
int caps_return2 = vx_dev_caps(DC_init->device(), VX_CAPS_NUM_WARPS, &NUM_WARPS_VX);
int caps_return3 = vx_dev_caps(DC_init->device(), VX_CAPS_NUM_CORES, &NUM_CORES_VX);


extern "C" {

cudaError_t cudaGetDevice(int *devPtr) { 
  *devPtr = 0;
  return cudaSuccess;
}

const char *cudaGetErrorName(cudaError_t error) { 
  return "SUCCESS\n";
}

cudaError_t cudaDeviceReset(void) { 
  scheduler_uninit(); 
  return cudaSuccess;
}

cudaError_t cudaDeviceSynchronize(void) { 
  cuSynchronizeBarrier(); 
  return cudaSuccess;
}

cudaError_t cudaThreadSynchronize(void) { 
  cuSynchronizeBarrier(); 
  return cudaSuccess;
}

cudaError_t cudaFreeHost(void *devPtr) { 
  free(devPtr);
  return cudaSuccess;
}

cudaError_t cudaMalloc(void **devPtr, size_t size) {
  auto DC = DeviceContext::instance();
  uint64_t mem_addr;  
  // RT_CHECK(vx_mem_alloc(DC->device(), size, VX_MEM_TYPE_GLOBAL, &mem_addr));
  // RT_CHECK(vx_mem_alloc(DC->device(), size, VX_MEM_READ_WRITE, (void** )&mem_addr));
  DC->dev_mem_alloc(size, VX_MEM_READ_WRITE, &mem_addr);
  
  DBG_PRINT("cudaMalloc: size=%ld, mem_addr=%p\n", size, mem_addr);
  *devPtr = (void*)mem_addr;
   return cudaSuccess;
}

cudaError_t cudaFree(void *devPtr) {
  auto DC = DeviceContext::instance(); 
  uint64_t mem_addr = (uint64_t)devPtr;  
  // vx_mem_free(DC->device(), mem_addr);
  DC->dev_mem_free(devPtr);
  
  DBG_PRINT("cudaFree: mem_addr=%lu\n", mem_addr);
  return cudaSuccess;
}

cudaError_t cudaMemset(void *devPtr, int value, size_t count) {  
  void* tmp_ptr;
  tmp_ptr = (void *) malloc(count);
  memset(tmp_ptr, value, count);

  auto DC = DeviceContext::instance();
  auto staging_buf = DC->staging_alloc(count);
  auto host_ptr = staging_buf.data();

  memcpy((char *)host_ptr, tmp_ptr, count);
  uint64_t mem_addr = (uint64_t)devPtr;
  // RT_CHECK(vx_copy_to_dev(DC->device(), mem_addr, host_ptr, count));
  DC->copy_to_dev(mem_addr, host_ptr, count);
  
  DBG_PRINT("cudaMemset: value=%d, dst=%lu, count=%ld\n", value, mem_addr, count);
  free(tmp_ptr);
  return cudaSuccess;
}

// cudaError_t cudaMemset(void *devPtr, int value, size_t count) {
//   auto DC = DeviceContext::instance();
//   auto staging_buf = DC->staging_alloc(count);
//   auto host_ptr = staging_buf.data();

//   // 정수 단위로 4바이트 정렬된 메모리에만 동작하는 memset 대체
//   if (count % sizeof(int) != 0) {
//     printf("cudaMemset: count (%lu) is not aligned to sizeof(int)\n", count);
//     return cudaErrorInvalidValue;
//   }

//   size_t num_ints = count / sizeof(int);
//   for (size_t i = 0; i < num_ints; ++i) {
//     host_ptr[i] = value;
//   }

//   uint64_t mem_addr = (uint64_t)devPtr;
//   DC->copy_to_dev(mem_addr, host_ptr, count);

//   printf("cudaMemset: int_value=%d, dst=%lu, count=%lu\n", value, mem_addr, count);
//   return cudaSuccess;
// }

cudaError_t cudaMemcpy(void *dst, const void *src, size_t count, cudaMemcpyKind kind) {
  int vx_err; 
  if (kind == cudaMemcpyHostToHost) {
    memcpy(dst, src, count);
  } else if (kind == cudaMemcpyDeviceToHost) {
    auto DC = DeviceContext::instance();
    auto staging_buf = DC->staging_alloc(count);
    auto host_ptr = staging_buf.data();
    uint64_t mem_addr = (uint64_t)src;
    //  RT_CHECK(vx_copy_from_dev(DC->device(), host_ptr, mem_addr, count));
    DC->copy_from_dev(mem_addr, host_ptr, count);
    memcpy(dst, (char*)host_ptr, count);
    DBG_PRINT("cudamemcpyDeviceToHost: src=%lu, dst=%p, count=%ld\n", mem_addr, dst, count);
  } else if (kind == cudaMemcpyHostToDevice) {
    auto DC = DeviceContext::instance();
    auto staging_buf = DC->staging_alloc(count);
    auto host_ptr = staging_buf.data();
    memcpy((char *)host_ptr, src, count);
    uint64_t mem_addr = (uint64_t)dst;
    DBG_PRINT("(memcpy_) host_ptr value: %d %d, addr: %ld\n", *(char *)src, *(char *)host_ptr, host_ptr);
    // RT_CHECK(vx_copy_to_dev(DC->device(), mem_addr, host_ptr, count));
    DC->copy_to_dev(mem_addr, host_ptr, count);

    DBG_PRINT("cudaMemcpyHostToDevice: src=%p, dst=%lu, count=%ld\n", src, mem_addr, count);
  } else if (kind == cudaMemcpyDeviceToDevice) {
    auto DC = DeviceContext::instance();
    auto staging_buf = DC->staging_alloc(count);
    auto host_ptr = staging_buf.data();
    uint64_t mem_src_addr = (uint64_t)src;
    // RT_CHECK(vx_copy_from_dev(DC->device(), host_ptr, mem_src_addr, count));
    DC->copy_from_dev(mem_src_addr, host_ptr, count);
    RT_CHECK(vx_ready_wait(DC->device(), 1000));
    uint64_t mem_dst_addr = (uint64_t)dst;
    // RT_CHECK(vx_copy_to_dev(DC->device(), mem_dst_addr, host_ptr, count));
    DC->copy_to_dev(mem_dst_addr, host_ptr, count);
    
    DBG_PRINT("cudaMemcpyDeviceToDevice: src=%lu, dst=%lu, count=%ld\n", mem_src_addr, mem_dst_addr, count);
  } else if (kind == cudaMemcpyDefault) {
    std::abort(); // not supported!
  }
  return cudaSuccess;
}


cudaError_t cudaMemcpyFromSymbol(void *dst, 
                                 const void *symbol, 
                                 size_t count, 
                                 size_t offset, 
                                 cudaMemcpyKind kind) {

// 2026 Feb 26, Currently not working!!!
    if (kind != cudaMemcpyDeviceToHost) {
        return cudaErrorInvalidValue;
    }

    std::string symbolName((char*)symbol);
    DBG_PRINT("cudaMemcpyFromSymbol: Looking for symbol '%s'\n", symbolName.c_str());

    std::fstream readfile;
    readfile.open("lookup_global_symbols.txt", std::ios::in);
    if (!readfile.is_open()) {
        printf("Error: Could not open lookup_global_symbols.txt\n");
        return cudaErrorFileNotFound;
    }

    std::string symbol_addr_str;
    std::string symbol_type_tmp;
    std::string symbol_name_tmp;
    uint64_t device_symbol_address = 0;
    bool found = false;

    while(readfile >> symbol_addr_str) {
        readfile >> symbol_type_tmp;
        std::getline(readfile, symbol_name_tmp);
        if (!symbol_name_tmp.empty() && symbol_name_tmp[0] == ' ') {
            symbol_name_tmp = symbol_name_tmp.substr(1);
        }

        if(symbolName == symbol_name_tmp) {
            device_symbol_address = std::stoull(symbol_addr_str, nullptr, 16);
            found = true;
            break;
        }
    }
    readfile.close();

    if (!found) {
        printf("Error: Symbol '%s' not found in lookup_global_symbols.txt\n", symbolName.c_str());
        return cudaErrorInvalidSymbol;
    }

    auto DC = DeviceContext::instance();
    uint64_t source_address = device_symbol_address + offset;

    DBG_PRINT("cudaMemcpyFromSymbol: Copying %zu bytes from device address 0x%llx to host address %p\n",
           count, source_address, dst);
    
    DC->copy_from_dev(source_address, dst, count);

    return cudaSuccess;
}


cudaError_t cudaMemcpyToSymbol_host(void *dst, 
                                    const void *src, 
                                    size_t count,
                                    size_t offset, 
                                    cudaMemcpyKind kind,
                                    void *symbol) {
                                      
  assert(offset == 0 && "DO not support offset !=0\n");

  //symbol is a pointer to a string 
  //print the string that symbol points to
  DBG_PRINT("(CudaMemcpytoSymbol) symbol name: %s\n", symbol);

  // if vector length of symbol_name_vector == 0
  //printf("symbol_name_vector.size(): %lu\n", symbol_name_vector.size());
  if(symbol_name_vector.size() == 0)
  {
    // cast symbol to string
    std::string symbol_name((char*)symbol);
    //split the string by space
    std::string delimiter = " ";
    std::string token;
    size_t pos = 0;
    while ((pos = symbol_name.find(delimiter)) != std::string::npos) {
      token = symbol_name.substr(0, pos);
      symbol_name_vector.push_back(token);
      symbol_name.erase(0, pos + delimiter.length());
    }
  }

  //pop first element in symbol_name_vector
  std::string symbol_name_looking = symbol_name_vector[0];
  DBG_PRINT("symbol name looking: %s\n", symbol_name_looking);  
  
  //open file lookup_global_symbols.txt to read
  std::fstream readfile;
  readfile.open("lookup_global_symbols.txt", std::ios::in);
  std::string symbol_type_tmp;
  std::string symbol_name_tmp;
  std::string symbol_addr_tmp;
  
  //print src value
  DBG_PRINT("src value at initial memcpytosymbol, addr: %p\n", src);
  DBG_PRINT("src value at initial memcpytosymbol %f\n", *((float*)src+1));

  while(readfile >> symbol_addr_tmp)
  {
    readfile >> symbol_type_tmp;
    std::getline(readfile, symbol_name_tmp);
    symbol_name_tmp = symbol_name_tmp.substr(1, symbol_name_tmp.size()-1);  
  
    DBG_COUT("debug : " << symbol_name_looking << " vs " << symbol_name_tmp << std::endl);

    if(symbol_name_looking == symbol_name_tmp)
    {
      DBG_COUT("found the symbol name in the lookup file, it is " << symbol_name_looking << " with the address of " << symbol_addr_tmp << std::endl);
      readfile.close();
      symbol_name_vector.erase(symbol_name_vector.begin());
      break;
    }
  }

  int vx_err;
  //cast string(in hex) to uint64_t
  uint64_t symbol_addr = std::stoull(symbol_addr_tmp, nullptr, 16);

  // print symbol_addr_tmp, and compare it with dst
  DBG_PRINT("symbol_addr_tmp: %p, dst: %p\n", symbol_addr, dst);

  //NOTE: old approach — allocate staging device memory and copy host data there
  //auto DC = DeviceContext::instance();
  //uint64_t mem_addr;
  //DC->dev_mem_alloc(count, VX_MEM_READ_WRITE, &mem_addr);
  //auto staging_buf = DC->staging_alloc(count);
  //auto host_ptr = staging_buf.data();
  //memcpy((char *)host_ptr, src, count);
  //DC->copy_to_dev(mem_addr, host_ptr, count);
  //memcpy_symbol_single.push_back(std::stoull(symbol_addr_tmp, nullptr, 16));
  //memcpy_symbol_single.push_back((uint64_t)mem_addr);
  //memcpy_symbol_single.push_back((uint64_t)count);
  //memcpy_symbol_single.push_back((uint64_t)offset);
  //memcpy_symbol.push_back(memcpy_symbol_single);
  //memcpy_symbol_single.clear();

  // New approach: store raw bytes in host memory, inline into args at launch
  // Update existing entry for same dst_addr (dedup), or add new entry.
  // Entries persist across kernel launches so BSS zeroing doesn't lose data.
  bool found_existing = false;
  for (auto &existing : memcpy_symbol) {
    if (existing.dst_addr == symbol_addr && existing.size == count) {
      memcpy(existing.data.data(), src, count);
      found_existing = true;
      DBG_PRINT("(cudamemcpytosymbol) updated existing: dst=0x%lx, size=%ld\n", symbol_addr, count);
      break;
    }
  }
  if (!found_existing) {
    MemcpySymbolEntry entry;
    entry.dst_addr = symbol_addr;
    entry.size = count;
    entry.data.resize(count);
    memcpy(entry.data.data(), src, count);
    memcpy_symbol.push_back(std::move(entry));
    DBG_PRINT("(cudamemcpytosymbol) saved inline: dst=0x%lx, size=%ld\n", symbol_addr, count);
  }
              
  return cudaSuccess;
}

cudaError_t cudaSetDevice(int device) {
  init_device();  
  return cudaSuccess;
}

cudaError_t cudaStreamCopyAttributes(cudaStream_t dst, cudaStream_t src) {
  cstreamData *dst_stream = (cstreamData *)dst;
  cstreamData *src_stream = (cstreamData *)src;

  if (dst_stream == NULL || src_stream == NULL) {
    return cudaErrorInvalidValue; // 1
  }

  dst_stream->stream_priority = src_stream->stream_priority;
  dst_stream->stream_flags = src_stream->stream_flags;

  return cudaSuccess; // 0
}

static int stream_counter = 1;
/*
  cudaStream_t is a Opaque Structure

  Overwrites cudaStream_t into custom cstreamData structure
  (does hardware uses the cudaStream_t stream)

*/
cudaError_t cudaStreamCreate(cudaStream_t *pStream) {
  cstreamData *s = (cstreamData *)calloc(1, sizeof(cstreamData));
  if (s == NULL)
    return cudaErrorMemoryAllocation;
  s->ev.status = C_RUN;
  s->id = stream_counter;
  stream_counter++;
  s->stream_priority = DEFAULT;
  create_KernelQueue(&(s->kernelQueue));

  INIT_LOCK(s->stream_lock);
  *pStream = (cudaStream_t)(s);

  return cudaSuccess;
}

cudaError_t cudaStreamDestroy(cudaStream_t stream) {
  cstreamData *s = (cstreamData *)(stream);

  free(s->kernelQueue);

  DESTROY_LOCK(s->stream_lock);

  free(s);

  return cudaSuccess;
}

cudaError_t cudaStreamSynchronize(cudaStream_t stream) {
  cstreamData *e = ((cstreamData *)(stream));
  MUTEX_LOCK(e->stream_lock);

  e->ev.status = C_SYNCHRONIZE;
  e->ev.numKernelsToWait = e->kernelQueue->waiting_count;
  MUTEX_UNLOCK(e->stream_lock);

  return cudaSuccess;
}

cudaError_t cudaGetDeviceCount(int *count) {
  // dummy value
  *count = 1;

  return cudaSuccess;
}

cudaError_t cudaGetDeviceProperties(cudaDeviceProp *deviceProp, int device) {

  // dummy values
  if (device == 0) {
    strcpy(deviceProp->name, "pthread");
    deviceProp->totalGlobalMem = 0;
    deviceProp->sharedMemPerBlock = 0;
    deviceProp->regsPerBlock = 0;
    deviceProp->warpSize = 0;
    deviceProp->memPitch = 0;
    deviceProp->maxThreadsPerBlock = 0;
    deviceProp->maxThreadsDim[0] = 1;
    deviceProp->maxThreadsDim[1] = 1;
    deviceProp->maxThreadsDim[2] = 1;

    deviceProp->maxGridSize[0] = 1;
    deviceProp->maxGridSize[1] = 1;
    deviceProp->maxGridSize[2] = 1;

    deviceProp->totalConstMem = 0;
    deviceProp->major = 0;
    deviceProp->minor = 0;
    deviceProp->clockRate = 0;
    deviceProp->textureAlignment = 0;
    deviceProp->deviceOverlap = false;
    deviceProp->multiProcessorCount = 0;
  }
  return cudaSuccess;
}

#ifndef cudaGetDeviceProperties
// Only define _v2 separately when CUDA headers don't macro-expand it
cudaError_t cudaGetDeviceProperties_v2(cudaDeviceProp *deviceProp, int device) {
  return cudaGetDeviceProperties(deviceProp, device);
}
#endif


static cudaError_t lastError = cudaSuccess;
const char *cudaGetErrorString(cudaError_t error) {
  if (error == cudaSuccess) {
    return "cudaSuccess";
  }
  return "unknown";
}

cudaError_t cudaGetLastError(void) { 
  return lastError; 
}

static callParams callParamTemp;

/*
  Internal Cuda Library Functions
*/
extern "C" {

extern cudaError_t CUDARTAPI __cudaPopCallConfiguration(dim3 *gridDim,
                                                        dim3 *blockDim,
                                                        size_t *sharedMem,
                                                        void **stream) {
  //  printf("__cudaPopCallConfiguration: Grid: x:%d y:%d z:%d Block: %d, %d, %d
  //  ShMem: %lu\n",
  // gridDim->x, gridDim->y, gridDim->z, blockDim->x, blockDim->y, blockDim->z,
  // *sharedMem);

  *gridDim = callParamTemp.gridDim;
  *blockDim = callParamTemp.blockDim;
  *sharedMem = callParamTemp.shareMem;
  *stream = callParamTemp.stream;

  // printf("__cudaPopCallConfiguration After : Grid: x:%d y:%d z:%d Block: %d,
  // %d, %d ShMem: %lu\n", gridDim->x, gridDim->y, gridDim->z, blockDim->x,
  // blockDim->y, blockDim->z, *sharedMem);

  // exit(1);

  return cudaSuccess;
}

extern __host__ __device__ unsigned CUDARTAPI __cudaPushCallConfiguration(
    dim3 gridDim, dim3 blockDim, size_t sharedMem = 0, void *stream = 0) {

  // printf("__cudaPushCallConfiguration Grid: x:%d y:%d z:%d Block: %d, %d, %d
  // "
  //        "ShMem: %lu\n ",
  //        gridDim.x, gridDim.y, gridDim.z, blockDim.x, blockDim.y, blockDim.z,
  //        sharedMem);

  // memory checks allocations
  callParamTemp.gridDim = gridDim;

  // std::cout << "assign gridDim" << std::endl;

  callParamTemp.blockDim = blockDim;
  //  std::cout << "assign blockDim" << std::endl;
  callParamTemp.shareMem = sharedMem;
  //  std::cout << "assign shareMem" << std::endl;
  (callParamTemp.stream) = stream;

  //  printf("__cudaPushCallConfiguration After Grid: x:%d y:%d z:%d Block: %d,
  //  %d, %d ShMem: %lu\n",
  //   gridDim.x, gridDim.y, gridDim.z, blockDim.x, blockDim.y, blockDim.z,
  //   sharedMem);

  // return 0 continues the Pop
  return cudaSuccess;

  // return ne 0 skips the Pop
}
} // extern C

cudaError_t cudaLaunchKernel_vortex(                          
                             const char *func, //-> kernel_name
                             dim3 gridDim, 
                             dim3 blockDim,
                             void **args, 
                             size_t sharedMem,
                             cudaStream_t stream,
                             const int num_args
                             ) {

  //open the file lookup.txt and load the content in the memory
  //cpp hash table, look for the kernel name, and retrieve the kerenl index
  
  //DEBUG PURPOSE
  DBG_COUT("RUNTIME FUNCTION" << std::endl);
  DBG_COUT("kernel_name: " << func << std::endl);
  DBG_COUT("number of arguments: " << num_args << std::endl);
  //reading lookup.txt
  std::fstream readfile;
  readfile.open("lookup.txt", std::ios::in);
  std::string kernel_idx_tmp;
  std::string kernel_name_tmp;

  // Strip mangling prefix to get the bare function name for matching.
  // Host func: _ZL19initiPKiS0_Pi → strip _Z, L, digits → initiPKiS0_Pi
  // Lookup:    L4initiPKiS0_Pi   → strip L, digits → initiPKiS0_Pi
  auto stripPrefix = [](const std::string &s) -> std::string {
    size_t i = 0;
    if (s.size() > 2 && s[0] == '_' && s[1] == 'Z') i = 2;
    while (i < s.size() && (s[i] == 'L' || (s[i] >= '0' && s[i] <= '9'))) i++;
    return s.substr(i);
  };
  std::string func_stripped = stripPrefix(std::string(func));
  DBG_COUT("func_stripped: " << func_stripped << std::endl);

  while(readfile >> kernel_idx_tmp) {
    readfile >> kernel_name_tmp;
    readfile.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
    std::string lookup_stripped = stripPrefix(kernel_name_tmp);
    DBG_COUT("debug : " << func_stripped << " vs " << lookup_stripped << std::endl);
    if(func_stripped == lookup_stripped) {
      DBG_COUT("found the kernel name in the lookup file, it is " << func << " with the index of " << std::stoi(kernel_idx_tmp) << std::endl);
      break;
    }
  }
  readfile.close();                    
                      
  DBG_PRINT("cudaLaunchKernel: gridDim=(%d, %d, %d), blockDim=(%d, %d, %d), sharedMem=%lu, num_args = %d\n",
    gridDim.x, gridDim.y, gridDim.z, blockDim.x, blockDim.y, blockDim.z, sharedMem, num_args);

  auto DC = DeviceContext::instance();
  DC->cleanup_args();

  int status = C_RUN;
  // upload kernel to device (reload when binary path changes)
  {
    // Use func as path if it looks like a file path (absolute or relative with /), else fallback
    std::string krnl_path = (strchr(func, '/') != nullptr) ? std::string(func) : "./kernel.vxbin";
    if (DC->get_krnl_buf() == nullptr || krnl_path != DC->last_krnl_path()) {
      DC->cleanup_krnl();
      RT_CHECK(vx_upload_kernel_file(DC->device(), krnl_path.c_str(), DC->krnl_buffer()));
      DC->set_last_krnl_path(krnl_path);
    }
  }


  // allocate staging buffer for kernel arguments
  size_t abuf_size = sizeof(kernel_arg_t) + ((num_args > 1) ? (sizeof(uint64_t) * (num_args - 1)) : 0);
  DBG_PRINT("(debug) abuf_size = %ld\n", abuf_size);

  //NOTE: old size calculation — 3 uint64_t per symbol (dst_addr, staging_addr, size)
  //size_t abuf_size_additional = (1 + memcpy_symbol.size() * 3) * sizeof(uint64_t);
  // New: count + per symbol (dst_addr, size, inline data padded to uint64_t)
  size_t abuf_size_additional = sizeof(uint64_t); // count field
  for (auto &entry : memcpy_symbol) {
    size_t data_slots = (entry.size + sizeof(uint64_t) - 1) / sizeof(uint64_t);
    abuf_size_additional += (2 + data_slots) * sizeof(uint64_t); // dst_addr + size + data
  }

  auto staging_buf = DC->staging_alloc(abuf_size+abuf_size_additional);

  auto abuf_ptr = (kernel_arg_t*)staging_buf.data();
  //auto abuf_ptr = (kernel_arg_t*)vx_host_ptr(staging_buf);
  assert(abuf_ptr);

  DBG_PRINT("*** kernel arg=%p, size=%ld\n", abuf_ptr, abuf_size);

  // write context
  context_t ctx;
  memset(&ctx, 0, sizeof(ctx));
  ctx.num_groups[0] = gridDim.x;
  ctx.num_groups[1] = gridDim.y; 
  ctx.num_groups[2] = gridDim.z; 
  ctx.local_size[0] = blockDim.x;
  ctx.local_size[1] = blockDim.y;
  ctx.local_size[2] = blockDim.z;
  ctx.global_offset[0] = 0;
  ctx.global_offset[1] = 0;
  ctx.global_offset[2] = 0;
  ctx.dyn_shared_mem_size = sharedMem;

  memcpy(&abuf_ptr->ctx, &ctx, sizeof(context_t));
  
  // write the kerenel index here it retrives
  abuf_ptr->kernel_idx = std::stoi(kernel_idx_tmp);
  abuf_ptr->num_args = num_args;
  
  // Mark Debug Check 
  //printf("test:: kernel_idx %d sizes: %d %d \n", abuf_ptr->kernel_idx, sizeof(kernel_arg_t), sizeof(context_t));
  //printf("address_check 0x%x, 0x%x, %d\n", &(ctx.num_groups[2]), &(ctx.global_offset[0]), &(ctx.global_offset[0])-&(ctx.num_groups[2]));
  //printf("address_check 0x%x, 0x%x, %d\n", &(ctx.global_offset[1]), &(ctx.global_offset[2]), &(ctx.global_offset[0])-&(ctx.num_groups[2]));
  //printf("global_offset 0x%x, 0x%x, %x\n", ctx.global_offset[0], ctx.global_offset[1], ctx.global_offset[2]);

  DBG_PRINT("*** kernel ctx: num_groups[0]=%d, num_groups[1]=%d\n", abuf_ptr->ctx.num_groups[0],abuf_ptr->ctx.num_groups[1]);

  // write arguments
  for (int i = 0; i < num_args; ++i) {    
    memcpy(&abuf_ptr->args[i], args[i], sizeof(uint64_t)); // 여기 체크 필요
    DBG_PRINT("*** cuda kernel args[%d]=0x%llx\n", i, (uint64_t)abuf_ptr->args[i]);
  }  

  //NOTE: old packing — 3 uint64_t per symbol (dst_addr, staging_dev_addr, size)
  //abuf_ptr->args[num_args] = memcpy_symbol.size();
  //int memcpy_symbol_idx = 0;
  //for (int i=num_args+1; i < num_args + (1 + memcpy_symbol.size() * 3); i+=3)
  //{
  //  memcpy(&abuf_ptr->args[i], &memcpy_symbol[memcpy_symbol_idx][0], sizeof(uint64_t));
  //  memcpy(&abuf_ptr->args[i+1], &memcpy_symbol[memcpy_symbol_idx][1], sizeof(uint64_t));
  //  memcpy(&abuf_ptr->args[i+2], &memcpy_symbol[memcpy_symbol_idx][2], sizeof(uint64_t));
  //  memcpy_symbol_idx++;
  //}

  // New packing: [count | dst_addr, size, inline_data... | dst_addr, size, inline_data... | ...]
  abuf_ptr->args[num_args] = memcpy_symbol.size();
  int slot = num_args + 1;
  for (auto &entry : memcpy_symbol) {
    abuf_ptr->args[slot++] = entry.dst_addr;
    abuf_ptr->args[slot++] = entry.size;
    size_t data_slots = (entry.size + sizeof(uint64_t) - 1) / sizeof(uint64_t);
    abuf_ptr->args[slot + data_slots - 1] = 0; // zero-pad last slot
    memcpy(&abuf_ptr->args[slot], entry.data.data(), entry.size);
    slot += data_slots;
  }
  // NOTE: Do NOT clear memcpy_symbol here. Vortex's vx_start.S zeroes the BSS
  // section on every kernel launch, which wipes device-side __device__ globals.
  // By keeping the symbol data, we re-send it with every kernel launch so that
  // the device-side memcpy in the wrapper restores the symbol values after BSS
  // zeroing. This fixes cfd and any other benchmark using cudaMemcpyToSymbol
  // with multiple kernel launches.
  // memcpy_symbol.clear();
  // upload additional information for cudaMemcpytoSymbol
  
  
  // auto staging_buf_additional = DC->staging_alloc(abuf_size_additional);
  // auto abuf_ptr_additional = (uint64_t*)staging_buf_additional.data();
  // abuf_ptr_additional[0] = memcpy_symbol.size();
  // printf("memcpy_symbol.size(): %lu\n", memcpy_symbol.size());
  // int abuf_ptr_additional_idx = 1;
  // while (abuf_ptr_additional_idx < memcpy_symbol.size()+1)
  // {
  //   memcpy(&abuf_ptr_additional[abuf_ptr_additional_idx*3-2], &memcpy_symbol[abuf_ptr_additional_idx-1][0], sizeof(uint64_t));
  //   memcpy(&abuf_ptr_additional[abuf_ptr_additional_idx*3-1], &memcpy_symbol[abuf_ptr_additional_idx-1][1], sizeof(uint64_t));
  //   memcpy(&abuf_ptr_additional[abuf_ptr_additional_idx*3], &memcpy_symbol[abuf_ptr_additional_idx-1][2], sizeof(uint64_t));
  //   abuf_ptr_additional_idx++;
  // }

  
  // upload kernel arguments
  // RT_CHECK(vx_copy_to_dev(DC->device(), KERNEL_ARG_BASE_ADDR, abuf_ptr, abuf_size));
  RT_CHECK(vx_upload_bytes(DC->device(), abuf_ptr, abuf_size+abuf_size_additional, DC->args_buffer()));
  DBG_PRINT("args_buffer: %p\n", DC->args_buffer());
  


  //RT_CHECK(vx_copy_to_dev(DC->device(), KERNEL_ARG_ADDITIONAL_INFO_BASE_ADDR, abuf_ptr_additional, abuf_size_additional));
  //DC->copy_to_dev(KERNEL_ARG_ADDITIONAL_INFO_BASE_ADDR, abuf_ptr_additional, abuf_size_additional);
  //RT_CHECK(vx_upload_bytes(DC->device(), abuf_ptr_additional, abuf_size_additional, (void**)KERNEL_ARG_ADDITIONAL_INFO_BASE_ADDR));
  

  DBG_PRINT("uploaded args\n");

  // ── DXA descriptor programming (before kernel launch) ──────────────────
  // Program DXA descriptors from the dxa_descriptors list.
  // Each entry: {slot, base_addr, size0, size1, stride0_bytes, tile0, tile1, elem_bytes}
  // Populated by cudaDxaProgramDesc2D() API calls from host code.
  for (auto &desc : dxa_descriptors) {
    DBG_PRINT("[DXA] Programming desc slot=%d, base=0x%lx, size=(%d,%d), stride=%d, tile=(%d,%d), elem=%d\n",
           desc.slot, desc.base_addr, desc.size0, desc.size1,
           desc.stride0_bytes, desc.tile0, desc.tile1, desc.elem_bytes);
    // DCR register layout for DXA descriptor (from vortex_bugfix/runtime/include/dxa.h)
    uint32_t dcr_base = 0x100 + desc.slot * 24; // VX_DCR_DXA_DESC_BASE + slot * VX_DCR_DXA_DESC_STRIDE
    uint32_t base_lo = (uint32_t)(desc.base_addr & 0xFFFFFFFF);
    uint32_t base_hi = (uint32_t)(desc.base_addr >> 32);
    // elem_size_enc = log2(elem_bytes)
    uint32_t esz = 0;
    { uint32_t b = desc.elem_bytes; while (b > 1) { b >>= 1; esz++; } }
    uint32_t meta = (2 << 0) | (esz << 3); // rank=2, elem_size_enc
    uint32_t tilesize01 = (desc.tile0 & 0xFFFF) | ((desc.tile1 & 0xFFFF) << 16);

    vx_dcr_write(DC->device(), dcr_base + 0, base_lo);       // BASE_LO_OFF
    vx_dcr_write(DC->device(), dcr_base + 1, base_hi);      // BASE_HI_OFF
    vx_dcr_write(DC->device(), dcr_base + 2, desc.size0);   // SIZE0_OFF
    vx_dcr_write(DC->device(), dcr_base + 3, desc.size1);   // SIZE1_OFF
    vx_dcr_write(DC->device(), dcr_base + 7, desc.stride0_bytes); // STRIDE0_OFF
    vx_dcr_write(DC->device(), dcr_base + 11, meta);        // META_OFF
    vx_dcr_write(DC->device(), dcr_base + 12, 1);           // ESTRIDE0_OFF
    vx_dcr_write(DC->device(), dcr_base + 13, 1);           // ESTRIDE1_OFF
    vx_dcr_write(DC->device(), dcr_base + 17, tilesize01);  // TILESIZE01_OFF
    vx_dcr_write(DC->device(), dcr_base + 20, 0);           // CFILL_OFF
  }
  dxa_descriptors.clear();

  // Auto-DXA: read dxa_descriptors.txt and program descriptors automatically
  load_dxa_auto_descriptors();
  for (auto &adesc : dxa_auto_descriptors) {
    // Match kernel name
    if (kernel_name_tmp.find(adesc.kernel_name) == std::string::npos &&
        adesc.kernel_name.find(kernel_name_tmp) == std::string::npos)
      continue;
    if (adesc.ptr_arg_idx < 0 || adesc.ptr_arg_idx >= num_args) continue;

    uint64_t base_addr = 0;
    memcpy(&base_addr, args[adesc.ptr_arg_idx], sizeof(uint64_t));

    uint32_t dim0 = 0, dim1 = 0;
    if (adesc.dim0_arg_idx >= 0 && adesc.dim0_arg_idx < num_args)
      memcpy(&dim0, args[adesc.dim0_arg_idx], sizeof(uint32_t));
    if (adesc.dim1_arg_idx >= 0 && adesc.dim1_arg_idx < num_args)
      memcpy(&dim1, args[adesc.dim1_arg_idx], sizeof(uint32_t));

    uint32_t stride = dim0 * adesc.elem_bytes;
    DBG_PRINT("[DXA-auto] slot=%d base=0x%lx size=(%d,%d) stride=%d tile=(%d,%d) elem=%d\n",
           adesc.slot, base_addr, dim0, dim1, stride, adesc.tile0, adesc.tile1, adesc.elem_bytes);

    uint32_t dcr_base = 0x100 + adesc.slot * 24;
    uint32_t esz = 0;
    { uint32_t b = adesc.elem_bytes; while (b > 1) { b >>= 1; esz++; } }
    uint32_t meta = (2 << 0) | (esz << 3);
    uint32_t tilesize01 = (adesc.tile0 & 0xFFFF) | ((adesc.tile1 & 0xFFFF) << 16);

    vx_dcr_write(DC->device(), dcr_base + 0,  (uint32_t)(base_addr & 0xFFFFFFFF));
    vx_dcr_write(DC->device(), dcr_base + 1,  (uint32_t)(base_addr >> 32));
    vx_dcr_write(DC->device(), dcr_base + 2,  dim0);
    vx_dcr_write(DC->device(), dcr_base + 3,  dim1);
    vx_dcr_write(DC->device(), dcr_base + 7,  stride);
    vx_dcr_write(DC->device(), dcr_base + 11, meta);
    vx_dcr_write(DC->device(), dcr_base + 12, 1);
    vx_dcr_write(DC->device(), dcr_base + 13, 1);
    vx_dcr_write(DC->device(), dcr_base + 17, tilesize01);
    vx_dcr_write(DC->device(), dcr_base + 20, 0);
  }


  // start execution
  RT_CHECK(vx_start(DC->device(), DC->get_krnl_buf(), DC->get_args_buf()));

  DBG_PRINT("wait device\n");
  // wait for the execution to complete
  RT_CHECK(vx_ready_wait(DC->device(), VX_MAX_TIMEOUT));

  // Read back __device__ variables from device memory after kernel execution.
  // These are registered as memcpy_symbol entries so they get restored
  // before the next kernel launch (surviving BSS zeroing).
  {
    static bool device_vars_registered = false;
    if (!device_vars_registered) {
      // Parse kernel_meta.log for DeviceVariables section
      std::ifstream meta("kernel_meta.log");
      DBG_PRINT("[device_var] meta file open=%d\n", meta.is_open());
      if (meta.is_open()) {
        std::string line;
        bool in_section = false;
        while (std::getline(meta, line)) {
          if (line == "DeviceVariables") { in_section = true; continue; }
          if (line == "END_DeviceVariables") { in_section = false; continue; }
          if (in_section) {
            std::istringstream iss(line);
            std::string name;
            uint64_t size;
            iss >> name >> size;
            // Strip C++ mangling prefix from kernel_meta.log name
            // e.g. _ZL4topL → topL (to match nm -C demangled names)
            auto stripMangle = [](const std::string &s) -> std::string {
              size_t i = 0;
              if (s.size() > 2 && s[0] == '_' && s[1] == 'Z') i = 2;
              while (i < s.size() && (s[i] == 'L' || (s[i] >= '0' && s[i] <= '9'))) i++;
              return s.substr(i);
            };
            std::string name_stripped = stripMangle(name);
            // Look up device address from lookup_global_symbols.txt
            std::ifstream sym("lookup_global_symbols.txt");
            std::string addr_s, type_s, sym_name;
            while (sym >> addr_s >> type_s) {
              std::getline(sym, sym_name);
              if (!sym_name.empty() && sym_name[0] == ' ')
                sym_name = sym_name.substr(1);
              if (sym_name == name_stripped) {
                uint64_t addr = std::stoull(addr_s, nullptr, 16);
                // Register as memcpy_symbol entry with current device value
                MemcpySymbolEntry entry;
                entry.dst_addr = addr;
                entry.size = size;
                entry.data.resize(size, 0);
                memcpy_symbol.push_back(std::move(entry));
                DBG_PRINT("[device_var] registered: %s (stripped=%s) addr=0x%lx size=%ld\n",
                          name.c_str(), name_stripped.c_str(), addr, size);
                break;
              }
            }
          }
        }
        device_vars_registered = true;
      }
    }
    // Read back only __device__ variable entries (not cudaMemcpyToSymbol ones).
    // device_var entries are appended at the end of memcpy_symbol by the
    // registration code above. Only read back those entries.
    static size_t device_var_start_idx = 0;
    if (device_vars_registered && device_var_start_idx == 0 && !memcpy_symbol.empty()) {
      // device vars were just registered — they're at the end
      // Find where they start by checking kernel_meta.log count
      std::ifstream meta2("kernel_meta.log");
      std::string line2;
      size_t dv_count = 0;
      bool in_sec = false;
      while (std::getline(meta2, line2)) {
        if (line2 == "DeviceVariables") { in_sec = true; continue; }
        if (line2 == "END_DeviceVariables") break;
        if (in_sec) dv_count++;
      }
      device_var_start_idx = memcpy_symbol.size() - dv_count;
    }
    if (device_vars_registered) {
      // Read back device vars using the kernel buffer handle.
      // BSS globals reside within the kernel binary's memory region.
      static uint64_t krnl_base_addr = 0;
      if (krnl_base_addr == 0 && DC->get_krnl_buf()) {
        vx_mem_address(DC->get_krnl_buf(), &krnl_base_addr);
        DBG_PRINT("[device_var] kernel base addr=0x%lx\n", krnl_base_addr);
      }
      for (size_t i = device_var_start_idx; i < memcpy_symbol.size(); i++) {
        auto &entry = memcpy_symbol[i];
        uint64_t offset = entry.dst_addr - krnl_base_addr;
        vx_copy_from_dev(entry.data.data(), DC->get_krnl_buf(), offset, entry.size);
        DBG_PRINT("[device_var] read-back[%ld]: addr=0x%lx offset=0x%lx\n",
               i, entry.dst_addr, offset);
      }
    }
  }

  DBG_PRINT("sync device\n");

  // dump performance counters for every kernel to a file
  
  int schedule = 0;
  int local_mem_use = 1;
    if (char *env = std::getenv("VORTEX_SCHEDULE_FLAG")) {
      schedule = std::stoi(std::string(env));
    }
    if (char *env = std::getenv("VORTEX_LOCALMEM_FLAG")) {
      local_mem_use = std::stoi(std::string(env));
    }
  
  std::string filename;
  if(schedule == 2)
  {
    filename = "Perf_counter_" + std::to_string(NUM_CORES_VX) + "C_" + std::to_string(NUM_WARPS_VX) + "W_" + std::to_string(NUM_THREADS_VX) + "T_SCHE_"+ std::to_string(schedule) +"_LOCAL_MEM_"+ std::to_string(local_mem_use) + ".txt";
  }
  else
  {
    filename = "Perf_counter_" + std::to_string(NUM_CORES_VX) + "C_" + std::to_string(NUM_WARPS_VX) + "W_" + std::to_string(NUM_THREADS_VX) + "T_SCHE_"+ std::to_string(schedule) + ".txt";
  }

  std::cout << "output file: " << filename << std::endl;
  //convert filename to char* with its content
  char filename_char[filename.size() + 1];
  strcpy(filename_char, filename.c_str());
  
  FILE *outputFile = fopen(filename_char, "a");
  if (outputFile == NULL) {
    perror("Error opening the output file");
  }
  vx_dump_perf(DC->device(), outputFile);
  
  return cudaSuccess;
}

}