KERNEL_CU    = kernel/kernel_gpu_cuda_all.cu
RUN_ARGS     = file ../../data/b+tree/mil.txt command ../../data/b+tree/command.txt
CI_RUN_ARGS  = file ../../data/b+tree/mil.txt command ../../data/b+tree/command.txt
EXTRA_C_SRCS = ./util/num/num.c ./main.c
include ../common.mk
