// cp_async_test.cu — Test cp.async → DXA automatic transformation
//
// Uses inline PTX for cp.async (avoids cuda_pipeline.h host issues).
// CuPBoP's kernelTranslator should detect inline asm "cp.async.*"
// and replace them with DXA issue + barrier calls.

#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <cuda.h>

#ifndef TILE_SIZE
#define TILE_SIZE 8
#endif

#ifndef MATRIX_SIZE
#define MATRIX_SIZE 16
#endif

// Host-side DXA descriptor programming
// DXA descriptors auto-programmed from dxa_descriptors.txt — no manual API needed

// Device-side cp.async wrappers using inline PTX
__device__ void cp_async_4(void* smem, const void* gmem) {
#ifdef __CUDA_ARCH__
    unsigned smem_addr = static_cast<unsigned>(__cvta_generic_to_shared(smem));
    asm volatile("cp.async.ca.shared.global [%0], [%1], 4;\n" :: "r"(smem_addr), "l"(gmem));
#endif
}
__device__ void cp_async_commit() {
#ifdef __CUDA_ARCH__
    asm volatile("cp.async.commit_group;\n" :::);
#endif
}
__device__ void cp_async_wait() {
#ifdef __CUDA_ARCH__
    asm volatile("cp.async.wait_group 0;\n" ::: "memory");
#endif
}

// Tiled SGEMM using cp.async for global→shared memory transfer
__global__ void sgemm_cp_async(const float* __restrict__ A,
                                const float* __restrict__ B,
                                float* __restrict__ C,
                                int N) {
    __shared__ float shA[TILE_SIZE][TILE_SIZE];
    __shared__ float shB[TILE_SIZE][TILE_SIZE];

    const int row = blockIdx.x * TILE_SIZE + threadIdx.x;
    const int col = blockIdx.y * TILE_SIZE + threadIdx.y;

    float sum = 0.0f;

    for (int k_base = 0; k_base < N; k_base += TILE_SIZE) {
        int a_row = blockIdx.x * TILE_SIZE + threadIdx.x;
        int a_col = k_base + threadIdx.y;
        int b_row = k_base + threadIdx.x;
        int b_col = blockIdx.y * TILE_SIZE + threadIdx.y;

        // cp.async: each thread copies 4 bytes (one float)
        if (a_row < N && a_col < N)
            cp_async_4(&shA[threadIdx.x][threadIdx.y], &A[a_row * N + a_col]);
        if (b_row < N && b_col < N)
            cp_async_4(&shB[threadIdx.x][threadIdx.y], &B[b_row * N + b_col]);

        cp_async_commit();
        cp_async_wait();
        __syncthreads();

        for (int k = 0; k < TILE_SIZE; ++k)
            sum += shA[threadIdx.x][k] * shB[k][threadIdx.y];

        __syncthreads();
    }

    if (row < N && col < N)
        C[row * N + col] = sum;
}

// CPU reference
void matmul_cpu(float* C, const float* A, const float* B, int N) {
    for (int i = 0; i < N; i++)
        for (int j = 0; j < N; j++) {
            float s = 0;
            for (int k = 0; k < N; k++)
                s += A[i * N + k] * B[k * N + j];
            C[i * N + j] = s;
        }
}

int main(int argc, char** argv) {
    int N = MATRIX_SIZE;
    if (argc > 1) N = atoi(argv[1]);
    if (N % TILE_SIZE != 0) { printf("N must be divisible by TILE_SIZE\n"); return 1; }

    printf("cp_async_test: N=%d, TILE_SIZE=%d\n", N, TILE_SIZE);

    size_t bytes = N * N * sizeof(float);
    float* h_A = (float*)malloc(bytes);
    float* h_B = (float*)malloc(bytes);
    float* h_C = (float*)malloc(bytes);
    float* h_ref = (float*)malloc(bytes);

    srand(42);
    for (int i = 0; i < N * N; i++) {
        h_A[i] = (float)rand() / RAND_MAX;
        h_B[i] = (float)rand() / RAND_MAX;
    }

    float *d_A, *d_B, *d_C;
    cudaMalloc(&d_A, bytes);
    cudaMalloc(&d_B, bytes);
    cudaMalloc(&d_C, bytes);
    cudaMemcpy(d_A, h_A, bytes, cudaMemcpyHostToDevice);
    cudaMemcpy(d_B, h_B, bytes, cudaMemcpyHostToDevice);

    // DXA descriptors auto-programmed from dxa_descriptors.txt (generated by kernelTranslator)
    // Manual calls removed — auto descriptor handles this.
    // cudaDxaProgramDesc2D(0, ..., d_A, ...);
    // cudaDxaProgramDesc2D(1, ..., d_B, ...);

    dim3 grid(N / TILE_SIZE, N / TILE_SIZE);
    dim3 block(TILE_SIZE, TILE_SIZE);
    sgemm_cp_async<<<grid, block>>>(d_A, d_B, d_C, N);

    cudaMemcpy(h_C, d_C, bytes, cudaMemcpyDeviceToHost);
    matmul_cpu(h_ref, h_A, h_B, N);

    int errors = 0;
    for (int i = 0; i < N * N; i++) {
        if (fabsf(h_C[i] - h_ref[i]) > 1e-3f * fmaxf(1.0f, fabsf(h_ref[i]))) {
            if (errors < 10) printf("MISMATCH [%d]: got %f, expected %f\n", i, h_C[i], h_ref[i]);
            errors++;
        }
    }
    printf("%s\n", errors == 0 ? "PASSED!" : "FAILED!");

    cudaFree(d_A); cudaFree(d_B); cudaFree(d_C);
    free(h_A); free(h_B); free(h_C); free(h_ref);
    return errors ? 1 : 0;
}
