name: build

on:
  push:
    paths-ignore:
      - '*.md'

  pull_request:
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"

      - name: Download vortex header
        run: |
          cd ${{ github.workspace }}
          wget https://www.dropbox.com/scl/fi/nd924ma3cq1fhauo0bs8x/vortex-header.tar.gz?rlkey=zudpp29yuxcrn42mxkiga8e06&dl=0
          tar -xzf 'vortex-header.tar.gz?rlkey=zudpp29yuxcrn42mxkiga8e06'
          cp vortex.h $CuPBoP_PATH/runtime/include

      - name: Download CUDA header files
        run: |
          cd ${{ github.workspace }}
          wget https://www.dropbox.com/s/r18io0zu3idke5p/cuda-header.tar.gz?dl=1
          tar -xzf 'cuda-header.tar.gz?dl=1'
          cp -r include/* runtime/threadPool/include/

      - name: Download CUDA files used for compiling NVVM IR
        run: |
          cd ${{ github.workspace }}
          wget https://www.dropbox.com/s/4pckqsjnl920gpn/cuda-10.1.tar.gz?dl=1
          tar -xzf 'cuda-10.1.tar.gz?dl=1'

      - name: Build project
        run: |
          cd ${{ github.workspace }}
          export CuPBoP_PATH=`pwd`
          export LD_LIBRARY_PATH=$CuPBoP_PATH/build/runtime:$CuPBoP_PATH/build/runtime/threadPool:$LD_LIBRARY_PATH
          mkdir build
          cd build
          cmake .. -DLLVM_CONFIG_PATH=`which llvm-config`
          make -j8
