# copied from MMCV (github.com/open-mmlab/mmcv)
name: lint

# File disabled
#on: [push, pull_request]
on:
  push:
    branches:
      - non-existent-branch
  pull_request:
    branches:
      - non-existent-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pre-commit hook
        run: |
          # markdownlint requires ruby >= 2.7
          sudo apt-add-repository ppa:brightbox/ruby-ng -y
          sudo apt-get update
          sudo apt-get install -y ruby2.7
          pip install pre-commit
          pre-commit install
      - name: Linting
        run: pre-commit run --all-files
